### PR TITLE
Editorial: Move this spec to ARIA monorepo

### PR DESCRIPTION
**Pull request by spectranaut**
In order to more easily keep track of the many ARIA specifications and spec changes, we are moving to an ARIA monorepo. We will merge this PR after [this PR to add the spec to ARIA](https://github.com/w3c/aria/pull/2191) and after we manually move over the open pull requests.

This repo will remain open for issue tracking, and the editor's draft will still be published here to maintain editor's draft URLs.

@AmeliaBR @IanPouncey - are you ok with this change?

### CODE REVIEW

**Comment by AmeliaBR** [comment]
For this & the equivalent issues on other repos:

If the ARIA WG has decided it's easier to keep things updated & coordinated in a monorepo, I don't have an object.

I'm concerned about the deletion of licence, code of conduct & contributing files, though: If this repo is being maintained for issue discussion & for publishing the compiled spec, those files should be kept, edited as needed.

I'm not really active in W3C spec work currently (as you can tell by it taking 2 months to notice this pull request). I'm not sure about Ian. So really: I defer to whatever the WG is doing, but that was my concern.

**Comment by cookiecrook** [comment]
When it's moved, please also move all the [issues](https://github.com/w3c/svg-aam/issues) I filed here.

**Comment by pkra** [comment]
@cookiecrook when the monorepo move was planned, the decision had been that issues are staying in the repositories. But the topic came up again on the editors call yesterday, so it might be revisited.

**Comment by spectranaut** [comment]
Hi @AmeliaBR -- The license file in the ARIA repo ([here](https://github.com/w3c/aria/blob/main/LICENSE.md)) will now cover the SVG-AAM, and the contributing document is about PR against the specification text and changes to the specification text, which is also outlined in the ARIA repository [here](https://github.com/w3c/aria/blob/main/CONTRIBUTING.md).

However, you have a good point about the code of conduct, I'll leave that in, thanks!

**Pull request merged**
