### PR TITLE
chore: github action to run prettier

### PR DESCRIPTION
**Pull request by pkra**
Matches w3c/graphics-aria#10, including dependabot for the action.

### CODE REVIEW

**Comment by pkra** [comment]
@daniel-montalvo would you know why the IRP check fails for me here?

**Comment by pkra** [comment]
Or rather: could I be added to the right group?

**Comment by pkra** [comment]
Oh, nevermind. I didn't realize the spec is owned by the SVG WG. Sorry for the noise.

**Comment by daniel-montalvo** [comment]
No worries.

 

 

---

Daniel Montalvo

Accessibility Specialist

W3C/WAI

**Comment by pkra** [comment]
Overcome by events.

**Pull request closed without merging**
